import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const lexendFont = localFont({
  src: [
    {
      path: "./fonts/Lexend/Lexend-Regular.ttf",
      weight: "400",
    },
    {
      path: "./fonts/Lexend/Lexend-Bold.ttf",
      weight: "700",
    },
  ],
  variable: "--font-lexend",
  preload: true,
});

const calFont = localFont({
  src: "./fonts/CalSans/CalSans-SemiBold.woff2",
  variable: "--font-cal",
  preload: true,
  display: "block",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lexendFont.variable} ${calFont.variable}`}>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
